### ISSUE TITLE
Finish RichCard conversions to Embeds and RichEmbeds 

### ISSUE THREAD

**Issue by stevengum97** [stevengum97/DiscordConnector#1]
- [ ] HeroCard
- [ ] ReceiptCard
- [x] AnimationCard
- [x] VideoCard
- [x] AudioCard
- [ ] ThumbnailCard
- [ ] AdaptiveCard
- [ ] SigninCard

**Comment by JasonSowers** [comment]
There are enough similarities between what BF offers and what discord offers as cards/embeds that this may be worth exploring again.
